### ISSUE TITLE
EMA Scheduler Restricted Access

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum-EMAScheduler#1]
Date: 4/4/2016
Time: 1:30 PM
Phone: DG2
Self reported smoking event which prompted EMA. Clicked "Ok" then got a notification that said "Your IT Admin has restricted access to the app - EMA Scheduler" and was not allowed to complete assessment.

**Comment by twhnat** [comment]
@DanielaGarza We are taking a look at the AirWatch platform to resolve this issue
