### ISSUE TITLE
EMA "Abandonded"

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum-EMAScheduler#3]
Date: 4/6/2016
Time: 11:26 AM
EMA considered "abandonded" before 10 minute total time was up.There is supposed to be a 10 minute time window for completion.
From User:
"I received an EMA at 11:26. I answered about 5 or so questions and then put it down. I went back at 11:34 and there was no option for me to finish the EMA."

**Comment by monowar** [comment]
earlier it was set to 5 minutes in the configuration. Now it is set to 10 minutes. Require to download configuration file again to see the effect
